name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '1.8.0'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-war
          path: target/*.war

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Download WAR artifact
        uses: actions/download-artifact@v2
        with:
          name: app-war

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null target/*.war ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ec2-user/apache-tomcat-9.0.106/webapps

      - name: Restart Tomcat
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '/home/ec2-user/apache-tomcat-9.0.106/bin/shutdown.sh && /home/ec2-user/apache-tomcat-9.0.106/bin/startup.sh'
